
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const blocks = [
"calendar-01","calendar-02","calendar-03","calendar-04","calendar-05","calendar-06","calendar-07","calendar-08","calendar-09","calendar-10","calendar-11","calendar-12","calendar-13","calendar-14","calendar-15","calendar-16","calendar-17","calendar-18","calendar-19","calendar-20","calendar-21","calendar-22","calendar-23","calendar-24","calendar-25","calendar-26","calendar-27","calendar-28","calendar-29","calendar-30","calendar-31","calendar-32","dashboard-01","demo-sidebar-controlled","demo-sidebar-footer","demo-sidebar-group-action","demo-sidebar-group-collapsible","demo-sidebar-group","demo-sidebar-header","demo-sidebar-menu-action","demo-sidebar-menu-badge","demo-sidebar-menu-collapsible","demo-sidebar-menu-sub","demo-sidebar-menu","demo-sidebar","login-01","login-02","login-03","login-04","login-05","sidebar-01","sidebar-02","sidebar-03","sidebar-04","sidebar-05","sidebar-06","sidebar-07","sidebar-08","sidebar-09","sidebar-10","sidebar-11","sidebar-12","sidebar-13","sidebar-14","sidebar-15","sidebar-16",
] as const;
