// This file is generated by Velite

import type config from '../velite.config.js'

type Collections = typeof config.collections

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]
