only_configured: true # only apply labels configured below

labels:
  bug:
    apply_when: A confirmed report of unexpected behavior in the application, only applied once the issue has been confirmed as valid
  docs:
    apply_when: A change or addition to the documentation
  duplicate:
    apply_when: This issue has already been raised/resolved
    context: similar_issues
  feature:
    apply_when: Adds new functionality/components
  chore:
    apply_when: Changes to the application which do not directly impact the end user
  "contributions welcome":
    apply_when: The issue is an easy fix that cannot be misinterpreted. Never apply this for big logic changes, or for issues that may take up someones time to work on and could even up with their work going unused.
    examples:
      - "The docs say `x`, but they should say `y`"
      - "There is a typo in the docs"
  dependencies:
    apply_when: A pull request updates a dependency or an issue is opened to update a dependency
  "awaiting submitter":
    apply_when: The issue or PR requires additional information or action from the submitter.
    removed_when: The submitter replies with the additional information or action requested
  "needs reproduction":
    apply_when: A reproduction is required to support the issue, or the provided reproduction is just steps and not a repository/stackblitz that maintainers can open. (Links to the official docs are fine)
  "has workaround":
    apply_when: The issue has a workaround available to end users provided in the description or in the comments. Never apply this label to enhancements, only to bugs.
  cli:
    apply_when: The issue relates/requires changes to the shadcn-svelte CLI
  triage:
    remove_when: The issue has been confirmed as a bug by the maintainer
    can_apply: false
  parity:
    apply_when: The request is for parity with upstream shadcn/ui
  slop:
    apply_when: The issue/pull request description is clearly generated by AI. Signs can be, usage of em-dashes, overly verbose descriptions that distract from the actual issue/changes, etc.
    remove_when: The issue/pull request description is no longer clearly generated by AI. Short no excessive use of em-dashes, no overly verbose descriptions that distract from the actual issue/changes.
