// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type gettingStarted = Collections['gettingStarted']['schema']['_output']
export declare const gettingStarted: gettingStarted[]

export type migration = Collections['migration']['schema']['_output']
export declare const migration: migration[]

export type components = Collections['components']['schema']['_output']
export declare const components: components[]

export type installation = Collections['installation']['schema']['_output']
export declare const installation: installation[]

export type darkMode = Collections['darkMode']['schema']['_output']
export declare const darkMode: darkMode[]

export type registry = Collections['registry']['schema']['_output']
export declare const registry: registry[]
