// This file is generated by Velite

export { default as gettingStarted } from './gettingStarted.json' with { type: 'json' }
export { default as migration } from './migration.json' with { type: 'json' }
export { default as components } from './components.json' with { type: 'json' }
export { default as installation } from './installation.json' with { type: 'json' }
export { default as darkMode } from './darkMode.json' with { type: 'json' }
export { default as registry } from './registry.json' with { type: 'json' }