<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";

	import { SidebarMenuButton, SidebarMenuItem } from "$lib/registry/ui/sidebar/index.js";
	import SidebarSection from "./sidebar-section.svelte";
</script>

<div class="grid w-full grid-cols-2 gap-4 xl:gap-6">
	<SidebarSection label="Overview" class="xl:col-start-1 xl:row-start-2">
		<SidebarMenuItem>
			<SidebarMenuButton isActive={true}>
				<IconPlaceholder
					lucide="ChartLineIcon"
					tabler="IconChartLine"
					hugeicons="Analytics01Icon"
					phosphor="ChartLineIcon"
					remixicon="RiLineChartLine"
				/>
				Analytics
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="ArrowLeftRightIcon"
					tabler="IconArrowsLeftRight"
					hugeicons="ArrowDataTransferHorizontalIcon"
					phosphor="ArrowsLeftRightIcon"
					remixicon="RiArrowLeftRightLine"
				/>
				Transactions
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="TrendingUpIcon"
					tabler="IconTrendingUp"
					hugeicons="AnalyticsUpIcon"
					phosphor="TrendUpIcon"
					remixicon="RiLineChartLine"
				/>
				Investments
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="Building2Icon"
					tabler="IconBuildingBank"
					hugeicons="BankIcon"
					phosphor="BankIcon"
					remixicon="RiBankLine"
				/>
				Accounts
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="PieChartIcon"
					tabler="IconChartPie"
					hugeicons="PieChartIcon"
					phosphor="ChartPieIcon"
					remixicon="RiPieChartLine"
				/>
				Spending
			</SidebarMenuButton>
		</SidebarMenuItem>
	</SidebarSection>

	<SidebarSection label="Planning" class="xl:col-start-1 xl:row-start-1">
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="FileTextIcon"
					tabler="IconFileText"
					hugeicons="File02Icon"
					phosphor="FileTextIcon"
					remixicon="RiFileTextLine"
				/>
				Documents
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="WalletIcon"
					tabler="IconWallet"
					hugeicons="Wallet01Icon"
					phosphor="WalletIcon"
					remixicon="RiWalletLine"
				/>
				Budget
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="ChartBarIcon"
					tabler="IconChartBar"
					hugeicons="ChartBarLineIcon"
					phosphor="ChartBarIcon"
					remixicon="RiBarChartLine"
				/>
				Reports
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="TargetIcon"
					tabler="IconTarget"
					hugeicons="Target02Icon"
					phosphor="TargetIcon"
					remixicon="RiFocus3Line"
				/>
				Goals
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="CalendarIcon"
					tabler="IconCalendar"
					hugeicons="Calendar03Icon"
					phosphor="CalendarIcon"
					remixicon="RiCalendarLine"
				/>
				Calendar
			</SidebarMenuButton>
		</SidebarMenuItem>
	</SidebarSection>

	<SidebarSection label="Support" class="flex xl:col-start-2 xl:row-start-1">
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="HelpCircleIcon"
					tabler="IconHelpCircle"
					hugeicons="HelpCircleIcon"
					phosphor="QuestionIcon"
					remixicon="RiQuestionLine"
				/>
				Help Center
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="BookOpenIcon"
					tabler="IconBook"
					hugeicons="BookOpen02Icon"
					phosphor="BookOpenIcon"
					remixicon="RiBookOpenLine"
				/>
				Docs
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="MessageSquareIcon"
					tabler="IconMessage"
					hugeicons="Message01Icon"
					phosphor="ChatCircleIcon"
					remixicon="RiChat1Line"
				/>
				Contact Us
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="ActivityIcon"
					tabler="IconActivity"
					hugeicons="ActivityIcon"
					phosphor="PulseIcon"
					remixicon="RiPulseLine"
				/>
				Status
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="GlobeIcon"
					tabler="IconWorld"
					hugeicons="Globe02Icon"
					phosphor="GlobeIcon"
					remixicon="RiGlobalLine"
				/>
				Community
			</SidebarMenuButton>
		</SidebarMenuItem>
	</SidebarSection>

	<SidebarSection label="Account" class="flex xl:col-start-2 xl:row-start-2">
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="UserIcon"
					tabler="IconUser"
					hugeicons="UserIcon"
					phosphor="UserIcon"
					remixicon="RiUserLine"
				/>
				Profile
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton isActive={true}>
				<IconPlaceholder
					lucide="CreditCardIcon"
					tabler="IconCreditCard"
					hugeicons="CreditCardIcon"
					phosphor="CreditCardIcon"
					remixicon="RiBankCardLine"
				/>
				Billing
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="BellIcon"
					tabler="IconBell"
					hugeicons="Notification03Icon"
					phosphor="BellIcon"
					remixicon="RiNotificationLine"
				/>
				Notifications
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="ShieldIcon"
					tabler="IconShield"
					hugeicons="ShieldIcon"
					phosphor="ShieldIcon"
					remixicon="RiShieldLine"
				/>
				Security
			</SidebarMenuButton>
		</SidebarMenuItem>
		<SidebarMenuItem>
			<SidebarMenuButton>
				<IconPlaceholder
					lucide="PaletteIcon"
					tabler="IconPalette"
					hugeicons="PaintBoardIcon"
					phosphor="PaletteIcon"
					remixicon="RiPaletteLine"
				/>
				Appearance
			</SidebarMenuButton>
		</SidebarMenuItem>
	</SidebarSection>
</div>
