name: Feature request
description: Request a new feature
labels: ["type: feature"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please make sure you have checked all of the following.
      options:
        - label: This feature already exists in [shadcn/ui](https://github.com/shadcn/ui) - if not, it won't be considered here so don't continue with your issue.
          required: true

  - type: markdown
    attributes:
      value: |
        This project's goal is to remain aligned with [shadcn/ui](https://github.com/shadcn-ui/ui). If the feature you are requesting is not in the original shadcn/ui, it will not be considered here.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature. If you intend to submit a PR for this feature, tell us how in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
