// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const UI = {
"accordion": {
	name: "accordion",
	type: "registry:ui",
},
"alert": {
	name: "alert",
	type: "registry:ui",
},
"alert-dialog": {
	name: "alert-dialog",
	type: "registry:ui",
},
"aspect-ratio": {
	name: "aspect-ratio",
	type: "registry:ui",
},
"avatar": {
	name: "avatar",
	type: "registry:ui",
},
"badge": {
	name: "badge",
	type: "registry:ui",
},
"breadcrumb": {
	name: "breadcrumb",
	type: "registry:ui",
},
"button": {
	name: "button",
	type: "registry:ui",
},
"calendar": {
	name: "calendar",
	type: "registry:ui",
},
"card": {
	name: "card",
	type: "registry:ui",
},
"carousel": {
	name: "carousel",
	type: "registry:ui",
},
"checkbox": {
	name: "checkbox",
	type: "registry:ui",
},
"collapsible": {
	name: "collapsible",
	type: "registry:ui",
},
"command": {
	name: "command",
	type: "registry:ui",
},
"context-menu": {
	name: "context-menu",
	type: "registry:ui",
},
"data-table": {
	name: "data-table",
	type: "registry:ui",
},
"dialog": {
	name: "dialog",
	type: "registry:ui",
},
"drawer": {
	name: "drawer",
	type: "registry:ui",
},
"dropdown-menu": {
	name: "dropdown-menu",
	type: "registry:ui",
},
"form": {
	name: "form",
	type: "registry:ui",
},
"hover-card": {
	name: "hover-card",
	type: "registry:ui",
},
"input": {
	name: "input",
	type: "registry:ui",
},
"input-otp": {
	name: "input-otp",
	type: "registry:ui",
},
"label": {
	name: "label",
	type: "registry:ui",
},
"menubar": {
	name: "menubar",
	type: "registry:ui",
},
"navigation-menu": {
	name: "navigation-menu",
	type: "registry:ui",
},
"pagination": {
	name: "pagination",
	type: "registry:ui",
},
"popover": {
	name: "popover",
	type: "registry:ui",
},
"progress": {
	name: "progress",
	type: "registry:ui",
},
"radio-group": {
	name: "radio-group",
	type: "registry:ui",
},
"range-calendar": {
	name: "range-calendar",
	type: "registry:ui",
},
"resizable": {
	name: "resizable",
	type: "registry:ui",
},
"scroll-area": {
	name: "scroll-area",
	type: "registry:ui",
},
"select": {
	name: "select",
	type: "registry:ui",
},
"separator": {
	name: "separator",
	type: "registry:ui",
},
"sheet": {
	name: "sheet",
	type: "registry:ui",
},
"sidebar": {
	name: "sidebar",
	type: "registry:ui",
},
"skeleton": {
	name: "skeleton",
	type: "registry:ui",
},
"slider": {
	name: "slider",
	type: "registry:ui",
},
"sonner": {
	name: "sonner",
	type: "registry:ui",
},
"switch": {
	name: "switch",
	type: "registry:ui",
},
"table": {
	name: "table",
	type: "registry:ui",
},
"tabs": {
	name: "tabs",
	type: "registry:ui",
},
"textarea": {
	name: "textarea",
	type: "registry:ui",
},
"toggle": {
	name: "toggle",
	type: "registry:ui",
},
"toggle-group": {
	name: "toggle-group",
	type: "registry:ui",
},
"tooltip": {
	name: "tooltip",
	type: "registry:ui",
},
}
