#!/usr/bin/env tsx
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { watch } from "node:fs";
import { iconLibraries, type IconLibraryName } from "shadcn-svelte/icons";

const SEARCH_BASE = "src/";
const REGISTRY_BASE = "src/lib/registry";

/** Writes `content` to `filePath` only if it differs from what is on disk. */
async function writeFileIfChanged(filePath: string, content: string) {
	const existing = await fs.readFile(filePath, "utf-8").catch(() => null);
	if (existing === content) return false;
	await fs.writeFile(filePath, content);
	return true;
}

type IconUsage = Record<IconLibraryName, Set<string>>;

async function findSvelteFiles(dir: string) {
	const files: string[] = [];
	const entries = await fs.readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await findSvelteFiles(fullPath)));
		} else if (entry.isFile() && entry.name.endsWith(".svelte")) {
			files.push(fullPath);
		}
	}

	return files;
}

async function scanIconUsage() {
	const iconUsage = Object.fromEntries(
		Object.keys(iconLibraries).map((key) => [key, new Set<string>()])
	) as IconUsage;

	const searchBasesDir = path.join(process.cwd(), SEARCH_BASE);
	const files = await findSvelteFiles(searchBasesDir);

	for (const file of files) {
		const content = await fs.readFile(file, "utf-8");

		for (const [libraryName, config] of Object.entries(iconLibraries)) {
			const regex = new RegExp(`${config.name}=["']([^"']+)["']`, "g");
			let match;
			while ((match = regex.exec(content)) !== null) {
				iconUsage[libraryName as IconLibraryName].add(match[1]);
			}
		}
	}

	return iconUsage;
}

async function generateIconFiles(iconUsage: IconUsage) {
	const outputDir = path.join(process.cwd(), REGISTRY_BASE, "icons");

	const completedLibraries: { name: IconLibraryName; icons: string[]; written: number }[] = [];

	for (const [lib, config] of Object.entries(iconLibraries)) {
		const libraryName = lib as IconLibraryName;
		const icons = Array.from(iconUsage[libraryName]).sort();

		if (icons.length === 0) {
			continue;
		}

		const typeName = `${config.title.replace(/\s/g, "")}IconName`;
		const typeUnion = icons.map((icon) => `"${icon}"`).join(" | ");

		const indexFileContent = `// Auto-generated by scripts/build-icons.ts
export type ${typeName} = ${typeUnion};
`;

		const dirname = `__${libraryName}__`;
		const iconDir = path.join(outputDir, dirname);
		const iconOutputDir = path.join(outputDir, dirname);

		const iconFiles = icons.map((icon) => {
			const iconExport = iconLibraries[libraryName].export({ name: icon });
			const fileName = `${icon}.ts`;

			return {
				name: icon,
				fileName,
				path: path.join(iconOutputDir, fileName),
				content: `// Auto-generated by scripts/build-icons.ts\n${iconExport}\n`,
			};
		});

		await fs.mkdir(iconDir, { recursive: true });
		await fs.mkdir(outputDir, { recursive: true });
		// Only touch files whose content changed. Rewriting all ~800 wrappers on every run
		// makes Vite invalidate every one of them and triggers a storm of page reloads.
		let written = 0;
		if (await writeFileIfChanged(path.join(iconOutputDir, "index.ts"), indexFileContent)) {
			written++;
		}
		for (const iconFile of iconFiles) {
			if (await writeFileIfChanged(iconFile.path, iconFile.content)) written++;
		}

		// clean unused icon files
		const iconFileSet = new Set(["index.ts", ...iconFiles.map((iconFile) => iconFile.fileName)]);
		for (const existingIconFile of await fs.readdir(iconOutputDir)) {
			if (!iconFileSet.has(existingIconFile)) {
				await fs.rm(path.join(iconOutputDir, existingIconFile));
			}
		}

		completedLibraries.push({ name: libraryName, icons, written });
	}

	console.log("✓ Generated icon files:");

	for (const library of completedLibraries) {
		console.log(
			`  - ${library.name}: ${library.icons.length} icons (${library.written} file${library.written === 1 ? "" : "s"} written)`
		);
	}
}

async function main() {
	const iconUsage = await scanIconUsage();
	await generateIconFiles(iconUsage);
}

const isWatchMode = process.argv.includes("--watch");

if (isWatchMode) {
	const SEARCH_DIR = path.join(process.cwd(), SEARCH_BASE);

	await main();

	watch(SEARCH_DIR, { recursive: true }, (_, filename) => {
		if (!filename?.endsWith(".svelte")) return;
		if (filename.includes("registry/icons/__")) return;
		if (filename.includes("components/icon-placeholder")) return;
		main().catch((error) => {
			console.error("❌ Icons build failed:", error);
		});
	});
} else {
	await main();
}
