import fs from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import postcss from "postcss";
import prettier from "prettier";
import { rimraf } from "rimraf";
import {
	componentsJsonSchema,
	registryItemSchema,
	registrySchema,
	type Registry,
	type RegistryItemType,
} from "shadcn-svelte/schema";
import { PRESET_STYLES, type PresetConfig } from "shadcn-svelte/preset";

interface BuildRegistryItem {
	name: string;
	type: string;
	files: Array<{
		path: string;
	}>;
}
import { buildRegistry } from "./registry.js";
import { THEMES } from "../src/lib/registry/themes.js";
import { getColorsData } from "../src/lib/components/colors/colors.js";
import { toJSONSchema } from "zod";

const prettierConfig = await prettier.resolveConfig(import.meta.url);
if (!prettierConfig) throw new Error("Failed to resolve prettier config.");

const INTERNAL_REGISTRY_PATH = path.resolve("src", "lib", "registry");
const REGISTRY_PATH = path.resolve("static", "registry");
const STYLE_TEMP_BASE = path.join(REGISTRY_PATH, "temp", "style");

function writeFileWithDirs(
	filePath: string,
	data: string,
	options: Parameters<typeof fs.writeFileSync>[2] = {}
): void {
	// Create directory path if it doesn't exist
	const dirname = path.dirname(filePath);
	fs.mkdirSync(dirname, { recursive: true });

	// Write the file
	fs.writeFileSync(filePath, data, options);
}

export async function build(): Promise<void> {
	const registry = await buildRegistry();

	validateRegistry(registry);

	// build registry styles (each style gets its own temp dir with cn-* classes resolved)
	for (const style of PRESET_STYLES) {
		const styleTempDir = path.join(STYLE_TEMP_BASE, style);
		try {
			fs.mkdirSync(styleTempDir, { recursive: true });
			const styleRegistry = await rewriteRegistryForStyle(registry, style, styleTempDir);
			await buildRegistryJson(styleRegistry, style);
			await runRegistryBuild(style);
		} finally {
			rimraf.sync(styleTempDir);
			const registryJsonPath = path.resolve(`registry-${style}.json`);
			if (fs.existsSync(registryJsonPath)) {
				fs.rmSync(registryJsonPath);
			}
		}
	}
	rimraf.sync(STYLE_TEMP_BASE);

	// ----------------------------------------------------------------------------
	// Build __registry__/blocks.ts
	// ----------------------------------------------------------------------------
	rimraf.sync(path.resolve("src", "__registry__"));

	let blocksIndex = `
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const blocks = [
`; // Creates block index files
	for (const block of registry) {
		if (block.type !== "registry:block" || block.name.startsWith("chart-")) continue;

		blocksIndex += `"${block.name}",`;
	}

	blocksIndex += "\n] as const;\n";
	const blocksPath = path.resolve("src", "__registry__", "blocks.ts");
	writeFileWithDirs(blocksPath, blocksIndex);

	// ----------------------------------------------------------------------------
	// Build __registry__/index.js.
	// ----------------------------------------------------------------------------
	let index = `
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {`;

	// TODO: fix later - we should either add these calendar examples to
	// the `lib/registry/examples` dir, or... do something else?
	const CALENDAR_EXAMPLES = ["02", "13", "22", "24", "29"].map((n) => `calendar-${n}`);

	for (const item of registry as BuildRegistryItem[]) {
		if (item.type !== "registry:example" && !CALENDAR_EXAMPLES.includes(item.name)) {
			continue;
		}

		const resolveFiles = item.files.map((file: BuildRegistryItem["files"][0]) =>
			file.path.replace("src/", "../")
		);

		index += `
"${item.name}": {
	files: [${resolveFiles.map((filePath: string) => `"${filePath.replaceAll(path.sep, "/")}"`)}],
},`;
	}

	index += `
}
`;

	// Write style index.
	const registryPath = path.resolve("src", "__registry__", "index.js");
	rimraf.sync(registryPath);
	writeFileWithDirs(registryPath, index);

	// ----------------------------------------------------------------------------
	// Build registry/colors/index.json.
	// ----------------------------------------------------------------------------
	const colorsTargetPath = path.join(REGISTRY_PATH, "colors");
	rimraf.sync(colorsTargetPath);
	if (!fs.existsSync(colorsTargetPath)) {
		fs.mkdirSync(colorsTargetPath, { recursive: true });
	}

	const colorsData = getColorsData();

	writeFileWithDirs(
		path.join(colorsTargetPath, "index.json"),
		JSON.stringify(colorsData, null, "\t"),
		"utf-8"
	);

	// ----------------------------------------------------------------------------
	// Build registry/colors/[theme].json
	// ----------------------------------------------------------------------------

	for (const theme of THEMES) {
		writeFileWithDirs(
			path.join(REGISTRY_PATH, "colors", `${theme.name}.json`),
			JSON.stringify(theme, null, "\t"),
			"utf-8"
		);
	}

	// ----------------------------------------------------------------------------
	// Build static/schema.json
	// ----------------------------------------------------------------------------
	const componentsJSON = toJSONSchema(componentsJsonSchema);
	writeFileWithDirs(
		path.resolve("static", "schema.json"),
		JSON.stringify(componentsJSON, null, "\t")
	);

	const SCHEMA_DIR = path.resolve("static", "schema");
	writeFileWithDirs(
		path.resolve(SCHEMA_DIR, "registry.json"),
		JSON.stringify(toJSONSchema(registrySchema), null, "\t")
	);

	writeFileWithDirs(
		path.resolve(SCHEMA_DIR, "registry-item.json"),
		JSON.stringify(toJSONSchema(registryItemSchema), null, "\t")
	);
}

const CN_CLASS_SELECTOR = /^\.(cn-[\w-]+)$/;

/**
 * Parse style-<style>.css and extract .cn-* class rules with their @apply values.
 * Returns a map of cn-class-name -> tailwind utility classes string.
 */
function parseStyleCss(css: string): Record<string, string> {
	const styles: Record<string, string> = {};
	const root = postcss.parse(css);

	root.walkRules((rule) => {
		for (const selector of rule.selectors) {
			const match = selector.trim().match(CN_CLASS_SELECTOR);
			if (!match) continue;

			const className = match[1];
			const applyValues: string[] = [];

			rule.walkAtRules("apply", (atRule) => {
				applyValues.push(atRule.params.trim());
			});

			if (applyValues.length > 0) {
				styles[className] = applyValues.join(" ");
			}
		}
	});

	return styles;
}

function transformContentWithStyle(content: string, styleMap: Record<string, string>): string {
	// Replace longer class names first to avoid "cn-foo" matching inside "cn-foo-bar"
	// Use negative lookahead (?![-\\w]) so we only match whole class names, not substrings
	const entries = Object.entries(styleMap).sort(([a], [b]) => b.length - a.length);
	for (const [className, classes] of entries) {
		const escaped = className.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
		const regex = new RegExp(escaped + "(?![\\w-])", "g");
		content = content.replace(regex, classes);
	}
	return content;
}

const TEXT_EXTENSIONS = new Set([".svelte", ".ts", ".svelte.ts"]);

async function rewriteRegistryForStyle(
	registry: Awaited<ReturnType<typeof buildRegistry>>,
	style: PresetConfig["style"],
	styleTempDir: string
): Promise<Awaited<ReturnType<typeof buildRegistry>>> {
	const styleCssPath = path.resolve(INTERNAL_REGISTRY_PATH, "styles", `style-${style}.css`);
	const styleCss = fs.readFileSync(styleCssPath, "utf8");
	const styleMap = parseStyleCss(styleCss);

	const styleItems: Awaited<ReturnType<typeof buildRegistry>> = [];

	for (const item of registry) {
		if (!item.files?.length) {
			styleItems.push(item);
			continue;
		}

		const styleFiles: typeof item.files = [];

		for (const file of item.files) {
			const srcPath = path.resolve(file.path);
			const tempPath = path.join(styleTempDir, file.path);
			const tempDir = path.dirname(tempPath);

			fs.mkdirSync(tempDir, { recursive: true });

			const ext = path.extname(file.path);
			if (TEXT_EXTENSIONS.has(ext)) {
				let content = fs.readFileSync(srcPath, "utf8");
				content = transformContentWithStyle(content, styleMap);
				fs.writeFileSync(tempPath, content, "utf8");
			} else {
				fs.copyFileSync(srcPath, tempPath);
			}

			styleFiles.push({
				...file,
				path: path.relative(process.cwd(), tempPath),
			});
		}

		styleItems.push({ ...item, files: styleFiles });
	}

	return styleItems;
}

function validateRegistry(registry: Awaited<ReturnType<typeof buildRegistry>>) {
	const selfReferenced = registry.filter(
		(item) => item.registryDependencies?.includes(item.name) ?? false
	);
	const selfReferenceError = selfReferenced
		.map((item) => `Registry item '${item.name}' depends on itself`)
		.join("\n");
	if (selfReferenceError) {
		throw new Error(selfReferenceError);
	}
}

async function buildRegistryJson(
	registry: Awaited<ReturnType<typeof buildRegistry>>,
	style: PresetConfig["style"]
) {
	// ----------------------------------------------------------------------------
	// Build `registry.json` file.
	// ----------------------------------------------------------------------------
	const result = registrySchema.parse(
		{
			$schema: "./static/schema/registry.json",
			name: `shadcn-svelte/${style}`,
			homepage: "https://shadcn-svelte.com",
			aliases: {
				lib: "$lib/registry/lib",
				ui: "$lib/registry/ui",
				components: "./components",
				hooks: "$lib/registry/hooks",
				utils: "$lib/utils",
			},
			// TODO: remove when moving from `next` to `latest`
			overrideDependencies: ["vaul-svelte@next"],
			items: registry,
		} as Registry,
		// maintains the schema defined property order
		{ jitless: true }
	);

	const ITEM_TYPES: RegistryItemType[] = [
		"registry:ui",
		"registry:hook",
		"registry:style",
		"registry:lib",
		"registry:block",
		"registry:font",
	];
	const filteredItems = result.items.filter((item) => ITEM_TYPES.includes(item.type));
	const registryJsonPath = path.resolve(`registry-${style}.json`);

	const registryJson = JSON.stringify({ ...result, items: filteredItems }, null, "\t");
	const formatted = await prettier.format(registryJson, {
		...prettierConfig,
		filepath: registryJsonPath,
	});
	fs.writeFileSync(registryJsonPath, formatted, "utf8");
}

function runRegistryBuild(style: PresetConfig["style"]) {
	const cwd = process.cwd();
	const registryJsonPath = path.resolve(cwd, `registry-${style}.json`);
	const outputPath = path.resolve(cwd, "static", "registry", "styles", style);
	execSync(
		`pnpm shadcn-svelte registry build "${registryJsonPath}" --output "${outputPath}" -c "${cwd}"`,
		{
			cwd,
			stdio: ["pipe", "pipe", "inherit"],
		}
	);
}

if (process.argv.includes("build-registry")) {
	build();
}
