// Browser-safe re-export of preset utilities.
// Use `shadcn/preset` for client-side code.
export {
	PRESET_STYLES,
	PRESET_BASE_COLORS,
	PRESET_BASE_COLOR_KEYS,
	PRESET_THEMES,
	PRESET_THEME_KEYS,
	PRESET_ICON_LIBRARIES,
	PRESET_FONTS,
	PRESET_RADII,
	PRESET_MENU_ACCENTS,
	PRESET_MENU_COLORS,
	DEFAULT_PRESET_CONFIG,
	PRESET_CHART_COLORS,
	toBase62,
	fromBase62,
	encodePreset,
	decodePreset,
	isPresetCode,
	isValidPreset,
	generateRandomConfig,
	generateRandomPreset,
	type PresetConfig,
} from "./preset.js";
