<!-- eslint-disable-next-line svelte/no-at-html-tags -->
{@html `<pre class="shiki github-dark-default" style="background-color:#0d1117;color:#e6edf3" tabindex="0"><code data-line-numbers=""><span class="line"><span style="color:#FF7B72">@import</span><span style="color:#79C0FF"> url</span><span style="color:#E6EDF3">(</span><span style="color:#A5D6FF">"https://fonts.googleapis.com/css2?family=Geist+Mono:wght@100..900&#x26;family=Geist:wght@100..900&#x26;display=swap"</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FF7B72">@import</span><span style="color:#A5D6FF"> "tailwindcss"</span><span style="color:#E6EDF3">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#FF7B72">@import</span><span style="color:#A5D6FF"> "tw-animate-css"</span><span style="color:#E6EDF3">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#FF7B72">@custom-variant</span><span style="color:#E6EDF3"> dark (&#x26;:is(.dark *));</span></span>
<span class="line"></span>
<span class="line"><span style="color:#FF7B72">@import</span><span style="color:#A5D6FF"> "./themes.css"</span><span style="color:#E6EDF3">;</span></span>
<span class="line"></span>
<span class="line"><span style="color:#79C0FF">:root</span><span style="color:#E6EDF3"> {</span></span>
<span class="line"><span style="color:#FFA657">	--radius</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">0.625</span><span style="color:#FF7B72">rem</span><span style="color:#E6EDF3">;</span></span>
<span class="line"><span style="color:#FFA657">	--background</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.145</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--card</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--card-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.145</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--popover</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--popover-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.145</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--primary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--primary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--secondary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.97</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--secondary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--muted</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.97</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--muted-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.556</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--accent</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.97</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--accent-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--destructive</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.577</span><span style="color:#79C0FF"> 0.245</span><span style="color:#79C0FF"> 27.325</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--border</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.922</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--input</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.922</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--ring</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.708</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-1</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.646</span><span style="color:#79C0FF"> 0.222</span><span style="color:#79C0FF"> 41.116</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-2</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.6</span><span style="color:#79C0FF"> 0.118</span><span style="color:#79C0FF"> 184.704</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-3</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.398</span><span style="color:#79C0FF"> 0.07</span><span style="color:#79C0FF"> 227.392</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-4</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.828</span><span style="color:#79C0FF"> 0.189</span><span style="color:#79C0FF"> 84.429</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-5</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.769</span><span style="color:#79C0FF"> 0.188</span><span style="color:#79C0FF"> 70.08</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.145</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-primary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-primary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-accent</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.97</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-accent-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-border</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.922</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-ring</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.708</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#E6EDF3">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#79C0FF">.dark</span><span style="color:#E6EDF3"> {</span></span>
<span class="line"><span style="color:#FFA657">	--background</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.145</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--card</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--card-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--popover</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.269</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--popover-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--primary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.922</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--primary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--secondary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.269</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--secondary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--muted</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.269</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--muted-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.708</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--accent</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.371</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--accent-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--destructive</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.704</span><span style="color:#79C0FF"> 0.191</span><span style="color:#79C0FF"> 22.216</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--border</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3"> / </span><span style="color:#79C0FF">10</span><span style="color:#FF7B72">%</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--input</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3"> / </span><span style="color:#79C0FF">15</span><span style="color:#FF7B72">%</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--ring</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.556</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-1</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.488</span><span style="color:#79C0FF"> 0.243</span><span style="color:#79C0FF"> 264.376</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-2</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.696</span><span style="color:#79C0FF"> 0.17</span><span style="color:#79C0FF"> 162.48</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-3</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.769</span><span style="color:#79C0FF"> 0.188</span><span style="color:#79C0FF"> 70.08</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-4</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.627</span><span style="color:#79C0FF"> 0.265</span><span style="color:#79C0FF"> 303.9</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--chart-5</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.645</span><span style="color:#79C0FF"> 0.246</span><span style="color:#79C0FF"> 16.439</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.205</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-primary</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.488</span><span style="color:#79C0FF"> 0.243</span><span style="color:#79C0FF"> 264.376</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-primary-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-accent</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.269</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-accent-foreground</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.985</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-border</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">1</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3"> / </span><span style="color:#79C0FF">10</span><span style="color:#FF7B72">%</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#FFA657">	--sidebar-ring</span><span style="color:#E6EDF3">: </span><span style="color:#79C0FF">oklch</span><span style="color:#E6EDF3">(</span><span style="color:#79C0FF">0.439</span><span style="color:#79C0FF"> 0</span><span style="color:#79C0FF"> 0</span><span style="color:#E6EDF3">);</span></span>
<span class="line"><span style="color:#E6EDF3">}</span></span>
<span class="line"></span>
<span class="line"><span style="color:#FF7B72">@theme</span><span style="color:#E6EDF3"> inline {</span></span>
<span class="line"><span style="color:#E6EDF3">	--radius-sm: calc(var(--radius) - 4px);</span></span>
<span class="line"><span style="color:#E6EDF3">	--radius-md: calc(var(--radius) - 2px);</span></span>
<span class="line"><span style="color:#E6EDF3">	--radius-lg: var(--radius);</span></span>
<span class="line"><span style="color:#E6EDF3">	--radius-xl: calc(var(--radius) </span><span style="color:#FF7B72">+</span><span style="color:#E6EDF3"> 4px);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-background: var(--background);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-foreground: var(--foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-card: var(--card);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-card-foreground: var(--card-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-popover: var(--popover);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-popover-foreground: var(--popover-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-primary: var(--primary);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-primary-foreground: var(--primary-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-secondary: var(--secondary);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-secondary-foreground: var(--secondary-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-muted: var(--muted);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-muted-foreground: var(--muted-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-accent: var(--accent);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-accent-foreground: var(--accent-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-destructive: var(--destructive);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-border: var(--border);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-input: var(--input);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-ring: var(--ring);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-chart-1: var(--chart-1);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-chart-2: var(--chart-2);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-chart-3: var(--chart-3);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-chart-4: var(--chart-4);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-chart-5: var(--chart-5);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar: var(--sidebar);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-foreground: var(--sidebar-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-primary: var(--sidebar-primary);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-primary-foreground: var(--sidebar-primary-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-accent: var(--sidebar-accent);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-accent-foreground: var(--sidebar-accent-foreground);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-border: var(--sidebar-border);</span></span>
<span class="line"><span style="color:#E6EDF3">	--color-sidebar-ring: var(--sidebar-ring);</span></span>
<span class="line"><span style="color:#E6EDF3">	--font-sans: "Geist", </span><span style="color:#7EE787">sans-serif</span><span style="color:#E6EDF3">;</span></span>
<span class="line"><span style="color:#E6EDF3">	--font-mono: "Geist Mono", monospace;</span></span>
<span class="line"><span style="color:#E6EDF3">	--animate-accordion-up: </span><span style="color:#7EE787">accordion-up</span><span style="color:#E6EDF3"> 0</span><span style="color:#79C0FF">.2s</span><span style="color:#7EE787"> ease-out</span><span style="color:#E6EDF3">;</span></span>
<span class="line"><span style="color:#E6EDF3">	--animate-accordion-down: </span><span style="color:#7EE787">accordion-down</span><span style="color:#E6EDF3"> 0</span><span style="color:#79C0FF">.2s</span><span style="color:#7EE787"> ease-out</span><span style="color:#E6EDF3">;</span></span>
<span class="line"><span style="color:#E6EDF3">}</span></span></code></pre>`}
