name: Build Preview Deployment

# cancel in-progress runs on new commits to same PR (github.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Image cache setup
      - name: Setup Image cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules/.cache/imagetools"
          key: ${{ runner.os }}-image-cache-${{ hashFiles('**/src/lib/img') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: sites/docs/.svelte-kit/cloudflare
