name: Tailwind 3 Deployment
on:
  push:
    branches:
      - next-tailwind-3
    paths:
      - sites/docs/**
  workflow_dispatch:


jobs:
  deploy-production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Production Site to Cloudflare Pages
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm


      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: sites/docs
          command: pages deploy ./.svelte-kit/cloudflare --project-name=shadcn-svelte-tw-3
