name: Reproduire
on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reproduire:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Hebilicious/reproduire@4b686ae9cbb72dad60f001d278b6e3b2ce40a9ac # v0.0.9-mp
        with:
          label: needs reproduction
